[tool.poetry]
name = "demographic-data-analyzer"
version = "0.1.0"
description = ""
authors = ["Soniaseguin <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
